SHUFFLE_KEYS = True
SHUFFLE_PROXIES = True

# OKX withdraw settings
OKX_WITHDRAW_AMT = (0.0102, 0.011)

"""

1 - ETH-ERC20
8453 - ETH-Base

"""

OKX_WITHDRAW_CHAIN_ID = 8453  # ETH-Base...

# Bridge settings

# RELAY
RELAY_DEST_CHAIN_ID = 8453
RELAY_BRIDGE_AMOUNT_THRESHOLD = 0.004

RELAY_AMT_RANGE = [0.0001, 0.0004]

# NITRO
NITRO_FROM_TOKEN = "ETH"
NITRO_TO_TOKEN = "ETH"

NITRO_AMT_RANGE = [0.0001, 0.0004]

# ORBITER
ORBITER_FROM_TOKEN = "ETH"
ORBITER_TO_TOKEN = "ETH"

ORBITER_TO_CHAIN_ID = 8453  # 1-Ethereum, 8453-Base...
ORBITER_AMT_RANGE = [0.0001, 0.0004]  # min-max


# Swaps
SWAP_SLIPPAGE = 3  # in %

# BASESWAP
BASESWAP_AMT_RANGE = [0.0001, 0.0004]
BASESWAP_FROM_TOKEN = "ETH"

# SUSHISWAP
SUSHISWAP_AMT_RANGE = [0.0001, 0.0004]
SUSHISWAP_FROM_TOKEN = "ETH"


# Lendings

# AAVE
AAVE_AMT_RANGE = [0.0001, 0.0004]

# OKX key setup
OKX_API_KEY = ""
OKX_API_SECRET = ""
OKX_PASSPHRASE = ""

# Sleep settings
DELAY_BETWEEN_ACCOUNTS = (90, 180)
DELAY_BETWEEN_ACTIONS = (10, 15)
RATELIMIT_SAFE_SLEEP = (15, 30)
MAX_DST_WAIT_TIME = 3600

# Gas price setup
GAS_PRICE_MULTIPLIER = 1.02
GAS_LIMIT_MULTIPLIER = 1.02
ACCEPTABLE_L1_GWEI = 3.1
GAS_AMT_MULTIPLIER = 1.02

# Retries in applicable functions/methods
MAX_RETRIES = 3

COINBASE_REFERRAL_UUID = ""
REFERRAL_ADDR = ""

COINGECKO_API_KEY = ""
