SHUFFLE_KEYS = True
SHUFFLE_PROXIES = True

# OKX withdraw settings
OKX_WITHDRAW_AMT = (0.0102, 0.011)

"""

1 - ETH-ERC20
8453 - ETH-Base

"""

OKX_WITHDRAW_CHAIN_ID = 8453  # ETH-Base

# Bridge settings
RELAY_DEST_CHAIN_ID = 8453
RELAY_BRIDGE_AMOUNT_THRESHOLD = 0.004

NITRO_FROM_TOKEN = "ETH"
NITRO_TO_TOKEN = "ETH"

# OKX key setup
OKX_API_KEY = ""
OKX_API_SECRET = ""
OKX_PASSPHRASE = ""

# Sleep settings
DELAY_BETWEEN_ACCOUNTS = (120, 240)
DELAY_BETWEEN_ACTIONS = (10, 15)
RATELIMIT_SAFE_SLEEP = (15, 30)
MAX_DST_WAIT_TIME = 3600

# Gas price setup
GAS_PRICE_MULTIPLIER = 1.05
GAS_LIMIT_MULTIPLIER = 1.05
ACCEPTABLE_L1_GWEI = 3.1
GAS_AMT_MULTIPLIER = 1.05

# Retries in applicable functions/methods
MAX_RETRIES = 3

COINBASE_REFERRAL_UUID = ""
REFERRAL_ADDR = ""
